<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>

		<NoWarn>$(NoWarn);CS1591</NoWarn> <!-- temporary, disable warnings for undocumented public members -->

		<PackageId>Injure.Mods.Runtime</PackageId>
		<Description>game-facing mod runtime from the game framework/engine colloquially known as Injure</Description>
	</PropertyGroup>

	<ItemGroup>
		<!-- Injure internals: -->
		<ProjectReference Include="../../eng/Analyzers/Injure.DevAnalyzers/Injure.DevAnalyzers.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
		<InternalsVisibleTo Include="Injure.Mods.Runtime.Tests" />
		<InternalsVisibleTo Include="Injure.Mods.Runtime.Tests.Modif.E2e" />

		<!-- public packages: -->
		<ProjectReference Include="../Injure/Injure.csproj" />
		<ProjectReference Include="../Injure.Mods.Abstractions/Injure.Mods.Abstractions.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Include="../../native/pack/osx-arm64/libinjureclrprof.dylib" Pack="true" PackagePath="runtimes/osx-arm64/native/" />
		<None Include="../../native/pack/linux-x64/libinjureclrprof.so" Pack="true" PackagePath="runtimes/linux-x64/native/" />
		<None Include="../../native/pack/linux-arm64/libinjureclrprof.so" Pack="true" PackagePath="runtimes/linux-arm64/native/" />
	</ItemGroup>
</Project>
