// SPDX-FileCopyrightText: 2026 belshftl
// SPDX-License-Identifier: MIT

namespace Injure.Internals.Analyzers.Shared;

internal static class AttributeSources {
	public const string ClosedEnumAttributeDefaultIsInvalidName = "DefaultIsInvalid";
	public const string ClosedEnumAttributeCheckZeroNameName = "CheckZeroName";
	public const string ClosedEnumAttribute =
		@"// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace Injure.Internals.Analyzers.Attributes {
	[global::Microsoft.CodeAnalysis.EmbeddedAttribute]
	[global::System.AttributeUsage(global::System.AttributeTargets.Struct, AllowMultiple = false, Inherited = false)]
	internal sealed class ClosedEnumAttribute : global::System.Attribute {
		public bool DefaultIsInvalid { get; init; }
		public bool CheckZeroName { get; init; } = true;
	}
}
";
	public const string ClosedEnumAttributeMetadataName = "Injure.Internals.Analyzers.Attributes.ClosedEnumAttribute";
	public const string ClosedEnumAttributeFilename = "ClosedEnumAttribute.g.cs";

	public const string ClosedEnumMirrorAttributeSubsetName = "Subset";
	public const string ClosedEnumMirrorAttribute =
		@"// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace Injure.Internals.Analyzers.Attributes {
	[global::Microsoft.CodeAnalysis.EmbeddedAttribute]
	[global::System.AttributeUsage(global::System.AttributeTargets.Struct, AllowMultiple = false, Inherited = false)]
	internal sealed class ClosedEnumMirrorAttribute : global::System.Attribute {
		public global::System.Type MirrorType { get; }
		public bool Subset { get; init; }
		public ClosedEnumMirrorAttribute(global::System.Type mirrorType) {
			MirrorType = mirrorType;
		}
	}
}
";
	public const string ClosedEnumMirrorAttributeMetadataName = "Injure.Internals.Analyzers.Attributes.ClosedEnumMirrorAttribute";
	public const string ClosedEnumMirrorAttributeFilename = "ClosedEnumMirrorAttribute.g.cs";

	public const string ClosedFlagsAttributeDefaultIsInvalidName = "DefaultIsInvalid";
	public const string ClosedFlagsAttributeCheckZeroNameName = "CheckZeroName";
	public const string ClosedFlagsAttribute =
		@"// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace Injure.Internals.Analyzers.Attributes {
	[global::Microsoft.CodeAnalysis.EmbeddedAttribute]
	[global::System.AttributeUsage(global::System.AttributeTargets.Struct, AllowMultiple = false, Inherited = false)]
	internal sealed class ClosedFlagsAttribute : global::System.Attribute {
		public bool DefaultIsInvalid { get; init; }
		public bool CheckZeroName { get; init; } = true;
	}
}
";
	public const string ClosedFlagsAttributeMetadataName = "Injure.Internals.Analyzers.Attributes.ClosedFlagsAttribute";
	public const string ClosedFlagsAttributeFilename = "ClosedFlagsAttribute.g.cs";

	public const string ClosedFlagsMirrorAttributeSubsetName = "Subset";
	public const string ClosedFlagsMirrorAttribute =
		@"// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace Injure.Internals.Analyzers.Attributes {
	[global::Microsoft.CodeAnalysis.EmbeddedAttribute]
	[global::System.AttributeUsage(global::System.AttributeTargets.Struct, AllowMultiple = false, Inherited = false)]
	internal sealed class ClosedFlagsMirrorAttribute : global::System.Attribute {
		public global::System.Type MirrorType { get; }
		public bool Subset { get; init; }
		public ClosedFlagsMirrorAttribute(global::System.Type mirrorType) {
			MirrorType = mirrorType;
		}
	}
}
";
	public const string ClosedFlagsMirrorAttributeMetadataName = "Injure.Internals.Analyzers.Attributes.ClosedFlagsMirrorAttribute";
	public const string ClosedFlagsMirrorAttributeFilename = "ClosedFlagsMirrorAttribute.g.cs";

	public const string StronglyTypedIntAttribute =
		@"// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace Injure.Internals.Analyzers.Attributes {
	[global::Microsoft.CodeAnalysis.EmbeddedAttribute]
	[global::System.AttributeUsage(global::System.AttributeTargets.Struct, AllowMultiple = false, Inherited = false)]
	internal sealed class StronglyTypedIntAttribute : global::System.Attribute {
		public global::System.Type BackingType { get; }
		public StronglyTypedIntAttribute(global::System.Type backingType) {
			BackingType = backingType;
		}
	}
}
";
	public const string StronglyTypedIntAttributeMetadataName = "Injure.Internals.Analyzers.Attributes.StronglyTypedIntAttribute";
	public const string StronglyTypedIntAttributeFilename = "StronglyTypedIntAttribute.g.cs";
}
