<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<PublishAot>true</PublishAot>
		<InvariantGlobalization>true</InvariantGlobalization>

		<PackageId>Injure.Weaver</PackageId>
		<Description>WIP game framework/engine with first-class mod support - post-compile publicize/etc. tool for games</Description>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AsmResolver.DotNet" Version="6.0.0" />
	</ItemGroup>
</Project>
