<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>

		<NoWarn>$(NoWarn);CS1591</NoWarn> <!-- temporary, disable warnings for undocumented public members -->

		<PackageId>Injure.Mods.Abstractions</PackageId>
		<Description>mod-specific APIs and infrastructure from the game framework/engine colloquially known as Injure</Description>
	</PropertyGroup>

	<ItemGroup>
		<!-- Injure internals: -->
		<ProjectReference Include="../../eng/Analyzers/Injure.DevAnalyzers/Injure.DevAnalyzers.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
		<InternalsVisibleTo Include="Injure.Mods.Abstractions.Tests" />
		<InternalsVisibleTo Include="Injure.Mods.Runtime.Tests" />

		<!-- public packages: -->
		<ProjectReference Include="../Injure/Injure.csproj" />
		<InternalsVisibleTo Include="Injure.Mods.Runtime" />
	</ItemGroup>
</Project>
