<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<IsPackable>false</IsPackable>
		<PublishAot>true</PublishAot>
		<InvariantGlobalization>true</InvariantGlobalization>
		<TrimMode>full</TrimMode>
		<NoWarn>$(NoWarn);IL2104</NoWarn> <!-- Mono.Cecil has some trim warnings, but we don't use any of the problematic features -->
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="../Injure/Injure.csproj" />
		<ProjectReference Include="../Injure.Mods.Abstractions/Injure.Mods.Abstractions.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="xunit.v3.aot.mtp-v2" Version="4.0.0-pre.*" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="Xunit" />
		<AssemblyMetadata Include="ProjectRoot" Value="$(MSBuildProjectDirectory)" />
		<AssemblyMetadata Include="RepoRoot" Value="$([MSBuild]::GetDirectoryNameOfFileAbove($(MSBuildProjectDirectory), 'Injure.slnx'))" />
	</ItemGroup>
</Project>
