<Project>
	<PropertyGroup>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<Version>0.1.0-alpha.0</Version>
		<Authors>belshftl</Authors>
		<Copyright>Copyright (c) 2026 belshftl</Copyright>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<RepositoryUrl>https://github.com/belshftl/Injure</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
	</PropertyGroup>
</Project>
