// SPDX-FileCopyrightText: 2026 belshftl
// SPDX-License-Identifier: MIT

using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Injure.DevAnalyzers.Shared;

internal static class SourceGen {
	public static void RegisterPostInitializationSources(
		IncrementalGeneratorInitializationContext context,
		params (string Filename, string Source)[] sources
	) {
		context.RegisterPostInitializationOutput(ctx => {
				ctx.AddEmbeddedAttributeDefinition();
				foreach ((string filename, string source) in sources)
					ctx.AddSource(filename, SourceText.From(source, Encoding.UTF8));
			}
		);
	}

	// one output per target type; ForAttributeWithMetadataName can technically yield the same
	// symbol more than once, hence the dedup
	public static void RegisterTargetOutput<T>(
		IncrementalGeneratorInitializationContext context,
		IncrementalValuesProvider<T?> targets,
		Func<T, INamedTypeSymbol> getSymbol,
		string hintSuffix,
		Func<T, string> emit
	) where T : class {
		context.RegisterSourceOutput(
			targets.Collect(),
			(ctx, infos) => {
				HashSet<INamedTypeSymbol> seen = new(SymbolEqualityComparer.Default);
				foreach (T? info in infos) {
					if (info is null)
						continue;
					INamedTypeSymbol sym = getSymbol(info);
					if (!seen.Add(sym))
						continue;
					ctx.AddSource(Util.GetHintName(sym, hintSuffix), SourceText.From(emit(info), Encoding.UTF8));
				}
			}
		);
	}

	public static void AppendFileHeader(StringBuilder sb) {
		sb.AppendLine("// <auto-generated/>");
		sb.AppendLine("#nullable enable");
		sb.AppendLine("#pragma warning disable CS1591");
	}

	// opens the namespace and every containing type of sym; the caller then emits the declaration
	// of sym itself at one tab of indentation
	public static void OpenScopes(StringBuilder sb, INamedTypeSymbol sym) {
		string? ns = Util.GetNamespace(sym);
		if (ns is not null)
			sb.Append("namespace ").Append(ns).AppendLine(" {");
		foreach (string header in Util.GetContainingTypeHeaders(sym))
			sb.Append(header).AppendLine(" {");
	}

	public static void CloseScopes(StringBuilder sb, INamedTypeSymbol sym) {
		List<string> headers = Util.GetContainingTypeHeaders(sym);
		for (int i = headers.Count - 1; i >= 0; i--)
			sb.Append("} // ").AppendLine(headers[i]);
		string? ns = Util.GetNamespace(sym);
		if (ns is not null)
			sb.Append("} // ").AppendLine(ns);
	}

	public static void AppendGeneratedCodeAttribute(StringBuilder sb, string generatorName) =>
		sb.Append("\t[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"Injure.DevAnalyzers.")
			.Append(generatorName).Append("\", \"").Append(Constants.GeneratorVersion).AppendLine("\")]");
}
