<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<NoWarn>$(NoWarn);CS1591</NoWarn> <!-- temporary, disable warnings for undocumented public members -->

		<PackageId>Injure.Mods.Abstractions</PackageId>
		<Version>0.1.0-alpha.0</Version>
		<Authors>belshftl</Authors>
		<Description>mod-specific APIs and infrastructure from the game framework/engine colloquially known as Injure</Description>
		<Copyright>Copyright (c) 2026 belshftl</Copyright>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<RepositoryUrl>https://github.com/belshftl/Injure</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
	</PropertyGroup>

	<ItemGroup>
		<!-- Injure internals: -->
		<ProjectReference Include="../Injure.Internals.Analyzers/Injure.Internals.Analyzers.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
		<InternalsVisibleTo Include="Injure.Internals.ModRuntimeTests" />
		<InternalsVisibleTo Include="Injure.Internals.Tests" />

		<!-- public packages: -->
		<ProjectReference Include="../Injure/Injure.csproj" />
		<InternalsVisibleTo Include="Injure.Mods.Runtime" />
	</ItemGroup>
</Project>
