<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<IsPackable>false</IsPackable>

		<!-- running requires a separate launch script, so don't run this alongside a plain `dotnet test` -->
		<IsTestingPlatformApplication>false</IsTestingPlatformApplication>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="../../eng/Fixtures/IlFixture/IlFixture.csproj" />
		<ProjectReference Include="../../src/Injure/Injure.csproj" />
		<ProjectReference Include="../../src/Injure.Mods.Abstractions/Injure.Mods.Abstractions.csproj" />
		<ProjectReference Include="../../src/Injure.Mods.Runtime/Injure.Mods.Runtime.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="xunit.v3.mtp-v2" Version="4.0.0" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="Xunit" />
	</ItemGroup>
</Project>
