name: Build, test, package, and push

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  packages: write

concurrency:
  group: pack-${{ github.ref }}
  cancel-in-progress: true

env:
  DOTNET_VERSION: 10.0.x

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore

      - name: Build libmisc
        working-directory: native/misc
        run: make RID=linux-x64

      - name: Build
        run: dotnet build --no-restore -c Release

      - name: Test
        run: dotnet test --no-build -c Release

  build-native:
    needs: test
    strategy:
      fail-fast: false
      matrix:
        include:
          - rid: osx-arm64
            runs_on: macos-14
            libaudio_out_name: libinjureaudio.dylib
            libclrprof_out_name: libinjureclrprof.dylib
            libmisc_out_name: libinjuremisc.dylib
          - rid: linux-x64
            runs_on: ubuntu-24.04
            libaudio_out_name: libinjureaudio.so
            libclrprof_out_name: libinjureclrprof.so
            libmisc_out_name: libinjuremisc.so
          - rid: linux-arm64
            runs_on: ubuntu-24.04-arm
            libaudio_out_name: libinjureaudio.so
            libclrprof_out_name: libinjureclrprof.so
            libmisc_out_name: libinjuremisc.so
          # TODO:
          # - rid: osx-x64
          #   runs_on: macos-15-intel
          #   libaudio_out_name: libinjureaudio.dylib
          #   libclrprof_out_name: libinjureclrprof.dylib
          #   libmisc_out_name: libinjuremisc.dylib
          # - rid: win-x64
          #   runs_on: windows-2025
          #   libaudio_out_name: injureaudio.dll
          #   libclrprof_out_name: injureclrprof.dll
          #   libmisc_out_name: injuremisc.dll

    runs-on: ${{ matrix.runs_on }}

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install native deps for macOS
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install jack pkgconf
          echo "PKG_CONFIG_PATH=$(brew --prefix jack)/lib/pkgconfig:$PKG_CONFIG_PATH" >> "$GITHUB_ENV"

      - name: Install native deps for Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends libjack-jackd2-dev pkg-config

      - name: Build native
        working-directory: native
        run: make OUTDIR=stage MODE=release RID=${{ matrix.rid }}

      - name: Upload native artifact
        uses: actions/upload-artifact@v4
        with:
          name: native-${{ matrix.rid }}
          path: |
            native/stage/${{ matrix.libaudio_out_name }}
            native/stage/${{ matrix.libclrprof_out_name }}
            native/stage/${{ matrix.libmisc_out_name }}

  pack-and-push:
    needs: [test, build-native]
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Fetch artifact for osx-arm64
        uses: actions/download-artifact@v5
        with:
          name: native-osx-arm64
          path: native/pack/osx-arm64
          merge-multiple: true

      - name: Fetch artifact for linux-x64
        uses: actions/download-artifact@v5
        with:
          name: native-linux-x64
          path: native/pack/linux-x64
          merge-multiple: true

      - name: Fetch artifact for linux-arm64
        uses: actions/download-artifact@v5
        with:
          name: native-linux-arm64
          path: native/pack/linux-arm64
          merge-multiple: true

      - name: Pack Injure
        run: >
          dotnet pack src/Injure/Injure.csproj -c Release -o artifacts/nuget

      - name: Pack Injure.Analyzers
        run: >
          dotnet pack src/Injure.Analyzers/Injure.Analyzers.csproj -c Release -o artifacts/nuget

      - name: Pack Injure.Mods.Abstractions
        run: >
          dotnet pack src/Injure.Mods.Abstractions/Injure.Mods.Abstractions.csproj -c Release -o artifacts/nuget

      - name: Pack Injure.Mods.Analyzers
        run: >
          dotnet pack src/Injure.Mods.Analyzers/Injure.Mods.Analyzers.csproj -c Release -o artifacts/nuget

      - name: Pack Injure.Mods.Analyzers.CodeFixes
        run: >
          dotnet pack src/Injure.Mods.Analyzers.CodeFixes/Injure.Mods.Analyzers.CodeFixes.csproj -c Release -o artifacts/nuget

      - name: Pack Injure.Mods.Runtime
        run: >
          dotnet pack src/Injure.Mods.Runtime/Injure.Mods.Runtime.csproj -c Release -o artifacts/nuget

      - name: Add GitHub Packages source
        run: >
          dotnet nuget add source --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }}
          --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

      - name: Push packages
        run: >
          dotnet nuget push "artifacts/nuget/*.nupkg" --source github --skip-duplicate

# vim: sw=2 ts=2 sts=2 et
